version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: madras-mini-golf-db
    environment:
      POSTGRES_DB: madras_mini_golf
      POSTGRES_USER: mini_golf_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mini_golf_user -d madras_mini_golf"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: madras-mini-golf-app
    environment:
      DATABASE_URL: postgresql://mini_golf_user:dev_password_123@postgres:5432/madras_mini_golf
      NODE_ENV: development
      SESSION_SECRET: dev_session_secret_change_in_production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: